import type { QuickPanelState } from "./quick-panel-store";

export const quickPanelSelectors = {
  landingScreen: (state: QuickPanelState) => ({
    goToModeSelection: state.goToModeSelection,
  }),
  modeSelectionScreen: (state: QuickPanelState) => ({
    lastExportedAdvancedTarget: state.lastExportedAdvancedTarget,
    lastExportedMode: state.lastExportedMode,
    selectMode: state.selectMode,
    selectAdvancedTarget: state.selectAdvancedTarget,
  }),
  calibrationScreen: (state: QuickPanelState) => ({
    screenshot: state.screenshot,
    calibrationRect: state.calibrationRect,
    errorKey: state.errorKey,
    error: state.error,
    setScreenshot: state.setScreenshot,
    setCalibrationRect: state.setCalibrationRect,
    acceptCalibration: state.acceptCalibration,
    failImageProcessing: state.failImageProcessing,
  }),
  advancedCalibrationScreen: (state: QuickPanelState) => ({
    advancedCalibration: state.advancedCalibration,
    advancedButtonsCalibration: state.advancedButtonsCalibration,
    advancedDraft: state.advancedDraft,
    advancedButtonsDraft: state.advancedButtonsDraft,
    selectedAdvancedTarget: state.selectedAdvancedTarget,
    errorKey: state.errorKey,
    error: state.error,
    setError: state.setError,
    setAdvancedScreenshot: state.setAdvancedScreenshot,
    setAdvancedOuterRect: state.setAdvancedOuterRect,
    confirmAdvancedOuterRect: state.confirmAdvancedOuterRect,
    setAdvancedEnabledPanels: state.setAdvancedEnabledPanels,
    setAdvancedPanels: state.setAdvancedPanels,
    setAdvancedButtons: state.setAdvancedButtons,
    setAdvancedButtonPanels: state.setAdvancedButtonPanels,
    acceptAdvancedCalibration: state.acceptAdvancedCalibration,
    failImageProcessing: state.failImageProcessing,
  }),
  customizeScreen: (state: QuickPanelState) => ({
    selectedMode: state.selectedMode,
    activePreset: state.activePreset,
    image: state.image,
    transform: state.transform,
    setTransform: state.setTransform,
    exports: state.exports,
    isExporting: state.isExporting,
    isProcessingImage: state.isProcessingImage,
    noticeKey: state.noticeKey,
    errorKey: state.errorKey,
    error: state.error,
    goToCalibration: state.goToCalibration,
    goToAdvancedCalibration: state.goToAdvancedCalibration,
  }),
  customizeActions: (state: QuickPanelState) => ({
    activePreset: state.activePreset,
    image: state.image,
    isProcessingImage: state.isProcessingImage,
    setImage: state.setImage,
    startImageProcessing: state.startImageProcessing,
    finishImageProcessing: state.finishImageProcessing,
    failImageProcessing: state.failImageProcessing,
    resetFit: state.resetFit,
    startExport: state.startExport,
    finishExport: state.finishExport,
    failExport: state.failExport,
  }),
  resultScreen: (state: QuickPanelState) => ({
    exports: state.exports,
    goToLanding: state.goToLanding,
  }),
};
